In [2]:
import numpy as np #allias
# import numpy
# a = numpy.array()(numpy.function)

a = np.array((1,3,9,0,2))
print(a)

[1 3 9 0 2]


In [4]:
import numpy as np
b = np.array([1,3,5,7,9])
print(b)

['1' '3' '5' '7' '9']


In [10]:
np_arr = np.array([3,3,3,3,3.3,'hello',False])
print((np_arr[-1]))

a = False
print(bool(a))

False
False


In [11]:
np_arr = np.array([3,3,3,3,3.3,'hello',False])
print(bool(np_arr[-1]))

a = False
print(bool(a))

True
False


In [12]:
a = 0
print(bool(a))

False


In [13]:
a = '0'
print(bool(a))

True


In [15]:
a=np.zeros(5) #1d array
print(a)


[0. 0. 0. 0. 0.]


In [22]:
a = np.zeros((3,4))
print(a)
print(a.dtype)
print(type(a[0][0]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
<class 'numpy.float64'>


In [23]:
a =np.empty((2,3,4) , dtype = int)
print(a)

[[[-4625196817309499392 -4620693217682128896                    0
   -4625196817309499392]
  [ 4598175219545276416 -4620693217682128896  4602678819172646912
   -4625196817309499392]
  [ 4598175219545276416                    0  4602678819172646912
    4598175219545276416]]

 [[ 4598175219545276416  4602678819172646912                    0
    4598175219545276416]
  [-4625196817309499392  4602678819172646912 -4620693217682128896
    4598175219545276416]
  [-4625196817309499392                    0 -4620693217682128896
   -4625196817309499392]]]


In [24]:
a =np.empty(4 , dtype = int)
print(a)

[876632419         0         1        -1]


In [26]:
a =np.full((2,3,4) , fill_value=0, dtype = int)
print(a)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [27]:
a =np.full(4,5 ,dtype=int)
print(a)

[5 5 5 5]


In [30]:
a = np.arange(2 * 3 * 4, dtype = int).reshape((2,3,4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [33]:
a = np.arange(9, dtype = int).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
a = np.arange(3,12,3)
print(a)

[3 6 9]


In [32]:
a = np.linspace(0, 23, num=24, dtype=int).reshape((2,3,4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [39]:
a = np.linspace(3,12,1, dtype=int)
print(a)

[3]


In [ ]:
a = np.linspace(3,12,1, dtype=int)
print(a)

In [40]:
a = np.shape(a)
print(a)

(1,)


In [41]:
a = np.size(a)
print(a)

1


In [46]:
a = np.random.randint(0, 10,3)
print(a)

[7 6 5]


In [48]:
a = np.random.choice([0, 1], size=10)
print(a)

[1 1 0 0 0 1 0 0 1 0]


In [49]:
#corresponding elements
a = np.array([1,2,3,4])
b = np.array([1,3,5,7])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 2  5  8 11]
[ 0 -1 -2 -3]
[ 1  6 15 28]
[1.         0.66666667 0.6        0.57142857]


In [50]:
#list
a = [1,2,3,4]
b = [1,3,5,7]
print(a+b)
#

[1, 2, 3, 4, 1, 3, 5, 7]


In [54]:
a = np.random.randint(2, 5, 15)
b = np.random.randint(1,3,15)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[4 2 2 4 3 3 3 3 3 3 3 2 2 2 4]
[2 1 2 2 2 1 1 2 2 1 1 1 1 2 1]
[6 3 4 6 5 4 4 5 5 4 4 3 3 4 5]
[2 1 0 2 1 2 2 1 1 2 2 1 1 0 3]
[8 2 4 8 6 3 3 6 6 3 3 2 2 4 4]
[2.  2.  1.  2.  1.5 3.  3.  1.5 1.5 3.  3.  2.  2.  1.  4. ]


In [56]:
b = a.reshape((3,5))
print(b)

[[4 2 2 4 3]
 [3 3 3 3 3]
 [3 2 2 2 4]]


In [60]:
random_matrix = np.random.randint(1, 10, size=(3, 4))
print(random_matrix)

[[2 7 1 8]
 [5 2 7 8]
 [9 5 5 9]]


In [61]:
transposed_matrix = random_matrix.T
print(transposed_matrix)

[[2 5 9]
 [7 2 5]
 [1 7 5]
 [8 8 9]]


In [62]:
concatenate_matrix = np.random.randint(1, 10, size=(3, 4))

print(concatenate_matrix)

[[6 7 2 5]
 [4 5 8 9]
 [5 8 6 2]]


In [65]:
a = np.random.randint(2,16,6)
b = np.random.randint(1,19,6)
print(np.concatenate((a,b)))

[ 2 10  7  8  2 11  2  3  9  8  6  4]
