In [3]:
#create a 5*5 matrix of random integers(1-90)

import numpy as np
matrix = np.random.randint(1, 90, (5, 5))
print(matrix)



[[54 11  9 17 64]
 [73 70  7 21 31]
 [69 20 86 74 12]
 [28 48 81 70 79]
 [47 13 61 66 23]]


In [4]:
#find mean of values row and column wise

import numpy as np
matrix = np.random.randint(1, 90, (5, 5))
print(matrix)
print("Mean of values row wise: ", np.mean(matrix, axis=1))
print("Mean of values column wise: ", np.mean(matrix, axis=0))

[[17 13 41 61  4]
 [47 28 73 74 69]
 [ 9 58 84 41 35]
 [16 50 44 31 43]
 [84 77 64 77 42]]
Mean of values row wise:  [27.2 58.2 45.4 36.8 68.8]
Mean of values column wise:  [34.6 45.2 61.2 56.8 38.6]


In [5]:
#replace all even numbers with -1
import numpy as np
matrix = np.random.randint(1, 90, (5, 5))
print(matrix)
matrix[matrix % 2 == 0] = -1
print(matrix)

[[35 10 29 15 40]
 [78 51  5 65 75]
 [43 65 68 76 68]
 [30 75 20 69 66]
 [61 64 88 23 65]]
[[35 -1 29 15 -1]
 [-1 51  5 65 75]
 [43 65 -1 -1 -1]
 [-1 75 -1 69 -1]
 [61 -1 -1 23 65]]


In [6]:
#sort the array row amd column wise

import numpy as np
matrix = np.random.randint(1, 90, (5, 5))
print(matrix)
print("Sorted array row wise: ", np.sort(matrix, axis=1))
print("Sorted array column wise: ", np.sort(matrix, axis=0))


[[69 16 13 79 60]
 [31 56 68 71 17]
 [21 67 75 67 77]
 [74 62  3 61 52]
 [71  5 61 41 35]]
Sorted array row wise:  [[13 16 60 69 79]
 [17 31 56 68 71]
 [21 67 67 75 77]
 [ 3 52 61 62 74]
 [ 5 35 41 61 71]]
Sorted array column wise:  [[21  5  3 41 17]
 [31 16 13 61 35]
 [69 56 61 67 52]
 [71 62 68 71 60]
 [74 67 75 79 77]]


In [7]:
#find row and column wise sum seperately

import numpy as np
matrix = np.random.randint(1, 90, (5, 5))
print(matrix)
print("Row wise sum: ", np.sum(matrix, axis=1))
print("Column wise sum: ", np.sum(matrix, axis=0))

[[18 11 61 49 70]
 [79 14 30 59  3]
 [44 58 59 38 12]
 [55  8  5 47 52]
 [54 82 80 39 35]]
Row wise sum:  [209 185 211 167 290]
Column wise sum:  [250 173 235 232 172]


In [8]:
#count the numbers of -ve in each column

import numpy as np
matrix = np.random.randint(-90, 90, (5, 5))
print(matrix)
print("Number of -ve in each column: ", np.sum(matrix < 0, axis=0))

[[-63 -35 -42 -80  38]
 [ 17  23 -86 -88 -10]
 [ 53  24 -50  45 -86]
 [ 27 -83 -60 -61   8]
 [-53  49  -6 -38 -71]]
Number of -ve in each column:  [2 2 5 4 3]


In [9]:
import numpy as np
matrix = np.random.randint(1, 90, (5, 5))
print(matrix)
print("Number of -ve in each column: ", np.sum(matrix < 0, axis=0))

[[80 16 44 54 57]
 [58 20 44 12 23]
 [33 63 42 23 57]
 [22 45 82 37 76]
 [62 35 77 64 58]]
Number of -ve in each column:  [0 0 0 0 0]


In [12]:
#QUESTION-02

#create a 5*5 array (stock levels)
import numpy as np
stock_levels = np.random.randint(20, 80, (5, 5))
print(stock_levels)


[[72 67 21 60 58]
 [70 67 34 51 59]
 [34 61 62 26 79]
 [64 64 44 35 68]
 [54 77 48 22 69]]


In [11]:
# create another 5*5 array (demand)
import numpy as np
demand = np.random.randint(1, 90, (5, 5))
print(demand)

[[88 10 59  4 78]
 [46 89 82 34 72]
 [15 83 53 16 43]
 [ 8 73 41 36  2]
 [28 46 37 68 51]]


In [13]:
#Remaining stock = stock - demand
import numpy as np
remaining_stock = stock_levels - demand
print(remaining_stock)

[[-16  57 -38  56 -20]
 [ 24 -22 -48  17 -13]
 [ 19 -22   9  10  36]
 [ 56  -9   3  -1  66]
 [ 26  31  11 -46  18]]


In [14]:
# replace negative values ->0 ( out of stock)

import numpy as np
remaining_stock[remaining_stock < 0] = 0
print(remaining_stock)

modified = np.where(remaining_stock < 0, 0, remaining_stock)
print(modified)

[[ 0 57  0 56  0]
 [24  0  0 17  0]
 [19  0  9 10 36]
 [56  0  3  0 66]
 [26 31 11  0 18]]
[[ 0 57  0 56  0]
 [24  0  0 17  0]
 [19  0  9 10 36]
 [56  0  3  0 66]
 [26 31 11  0 18]]


In [15]:
#total shortage

import numpy as np
total_shortage = np.sum(np.where(remaining_stock * -1,))
print(total_shortage)

64


In [20]:
#PRODUCT WITH ZERO STOCK

import numpy as np
product_with_zero_stock = np.where(remaining_stock == 0)
print(product_with_zero_stock)

product_shortage = np.sum (np.where(modified == 0,1,0), axis = 0)
print(product_shortage)

(array([0, 0, 0, 1, 1, 1, 2, 3, 3, 4]), array([0, 2, 4, 1, 2, 4, 1, 1, 3, 3]))
[1 3 2 2 2]


In [21]:
# sort each row based on remaining stock

import numpy as np
sorted_remaining_stock = np.sort(remaining_stock, axis=1)
print(sorted_remaining_stock)

[[ 0  0  0 56 57]
 [ 0  0  0 17 24]
 [ 0  9 10 19 36]
 [ 0  0  3 56 66]
 [ 0 11 18 26 31]]


In [23]:
import pandas as pd
pd.read_csv('student_data.csv')

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
